### ISSUE TITLE
add documentation to Shiny modules

### ISSUE THREAD

**Issue by bzkrouse** [ASA-DIA-InteractiveSafetyGraphics/safetyGraphics#133]
Document the purpose and input/output parameters for each module.  Possibly using Roxygen comments

**Comment by jwildfire** [comment]
Would also be good to create a "Shiny Workflow" wiki page (or vignette?) that documents what each module does, and how they interact, at a fairly granular level. Kind of like this [webcharts life cycle wiki page](https://github.com/RhoInc/Webcharts/wiki/Webcharts-Life-Cycle).
