### ISSUE TITLE
Consider adding code formatting to our build process

### ISSUE THREAD

**Issue by jwildfire** [ASA-DIA-InteractiveSafetyGraphics/safetyGraphics#14]
```
install.packages("formatR")
formatR::tidy_dir("R")
```

**Comment by jwildfire** [comment]
Could also consider a linter: 
```
install.packages("lintr")
lintr::lint_package()
```

**Comment by pburnsdata** [comment]
[FormatR](https://yihui.name/formatr/) did improve indenting and spacing, but as the author notes "The tricks used in this packages are very dirty" (e.g. line breaks after the pipes are not preserved) so this seemed like something we may want to run prior to release under supervision, but not as part of our build process.

[lintr](https://github.com/jimhester/lintr) provided some nice suggestions and can integrate nicely with Travis (if we add it to our build process, it can [automatically provide comments on our PR](https://github.com/lockedata/HIBPwned/pull/30)). However, it has a lot of comments currently so it would require a decent amount of investment upfront to resolve these issues and puts the onus on the programmer to write with good style - so little more work than a code formatter.
