### ISSUE TITLE
Default Field level data doesn't work after custom mapping

### ISSUE THREAD

**Issue by jwildfire** [ASA-DIA-InteractiveSafetyGraphics/safetyGraphics#144]
Measure Values don't autofill when you customize the field level data and then load a fully standard data set.

### Steps to Recreate

1. Open the app, and load/switch to the partial SDTM data set
2. Fill in the needed settings on the settings page & view the chart to make sure it renders as expected
3. On the data tab, change back to the default AdAM data.
4. Change to the settings tab, and note that the measure value fields (Bilirubin, etc) are not filled in (shown below). 

![image](https://user-images.githubusercontent.com/3680095/51991197-77170080-245f-11e9-9a23-2e10de3d3a99.png)

**Comment by pburnsdata** [comment]
Will need to change generateSettings to include measure value columns

**Comment by jwildfire** [comment]
@pburnsdata  said: "Will need to change generateSettings to include measure value columns" 

Looking more closely now, and I'm actually not sure I follow this. Seems like these settings should be populated based on the matching standard in `generateSettings`  since there are defaults for the fields under `adam` and `sdtm` in the `settingsMetadata` data. In fact, it seems to work as expected (for ADaM) on initial load ... not sure why it then bombs for SDTM ...
