### ISSUE TITLE
Exported Code doesn't run 

### ISSUE THREAD

**Issue by jwildfire** [ASA-DIA-InteractiveSafetyGraphics/safetyGraphics#149]
The code exported in the widget doesn't currently work :(

**Comment by pburnsdata** [comment]
Yeah, this is expected - right now we have data$param as the data parameter (which will not exist in their workspace) so it won't work. But maybe we can think of a way to print the data without it being overkill or some other way to provide the data for the function call.

**Comment by bzkrouse** [comment]
@pburnsdata - had the same thought.  We could also provide example code for them to read the file into R. e.g. if file name is "data.csv" we could do:

```r
path <- "path_to_data"
my_data<- read.csv(file.path(path, "data.csv"))
eDISH(data = my_data, ....)
```

**Comment by pburnsdata** [comment]
@bzkrouse that's a neat idea. So we'd be preserving and passing the dataset name but providing some code and context for them to make it easier and more obvious that they need to edit it?
