### ISSUE TITLE
Change validateSettings() output from list to data frame

### ISSUE THREAD

**Issue by bzkrouse** [ASA-DIA-InteractiveSafetyGraphics/safetyGraphics#172]
since the DF would be 1 record per text_key per check, it could be useful to include a column for check type, e.g. required, numeric, etc.

**Comment by jwildfire** [comment]
Wondering if it is best to keep returning lists from the `checkXXX()` functions or change it so that they return tibbles. Leaning towards staying with lists (so we can keep using `map()` and friends) and then just coercing everything to a tibble at the end. Make sense, @bzkrouse?

**Comment by bzkrouse** [comment]
@jwildfire , makes sense!

**Comment by jwildfire** [comment]
for a validation object `v` with a single check `ch` I'm doing the following: 
- renaming `v$checkList` to `v$checks`
- renaming `ch$check` to `ch$description`
- adding `ch$type` which is (currently) "column", "field", "numeric" or "required"
- renaming the `checkXXX()` functions to match `ch$type` above (e.g. `checkColumnSetting()` -> `checkColumn()`
