### ISSUE TITLE
Drop unused rows and columns before initializing the chart

### ISSUE THREAD

**Issue by jwildfire** [ASA-DIA-InteractiveSafetyGraphics/safetyGraphics#19]

**Comment by jwildfire** [comment]
First: Test out performance with a big file, and determine best path forward

**Comment by jwildfire** [comment]
General approach: Add a function called `trimData()` that takes the raw data and a settings object and returns

**Comment by pburnsdata** [comment]
I just uploaded a ~40,000 version of adlbc (~11 MB) and it didn't allow the upload. Looks like this:
![image](https://user-images.githubusercontent.com/26064686/52368122-b1fad480-2a1b-11e9-951e-89fd0be3b4f3.png)

**Comment by jwildfire** [comment]
@pburnsdata Maybe 20mb? Anything much bigger than that and the app is going to get slow ... 

Is it kosher to change the settings in the package? Maybe we should make it an option for the wrapper, like `safetyGraphicsApp(maxFileSize=20)`, with the default being we don't change the option?

**Comment by pburnsdata** [comment]
@jwildfire It's a good question - I'm not really sure. @bzkrouse any thoughts? But I like the idea of exposing it to the user so they can change it- I think we can just throw an options(shiny.maxRequestSize=(max_size*1024^2)) at the top of dataUpload.R (or server.R if need be) with max_size defaulting to 20. 

Additionally, I'm thinking we either drop the unused rows and columns when a setting changes or when they click on the chart tab. Not 100% on which would be better at this point and I'm curious if it would affect the data tab and its data preview at all...
