### ISSUE TITLE
Modularize each tab in app

### ISSUE THREAD

**Issue by bzkrouse** [ASA-DIA-InteractiveSafetyGraphics/safetyGraphics#24]
Thoughts:
- If we want to extend this to other chart types in the future, we probably want to generate the settings UI elements conditional on chart type.  
- We also want to populate the UI elements based on data standard.
- This may require nested modules, e.g. generateSettings() vs. populateSettings()
- If we want to make a UI for eDISH only, desired approach may be to put the UI elements in the regular UI function and then fill them using the populateSettings() module

**Comment by jwildfire** [comment]
As discussed the other day, I think your thoughts above are heading in the right direction. We definitely do want to support multiple chart types in v2.0 of the app. And I do think we'll eventually want to create a `generateSettingsUI()` function that either takes a list of chart types, or perhaps just a list of the settings themselves (perhaps along with some meta data about the settings). 

The function should then generate a single Settings UI page that can be used to generate all of the charts (as opposed to creating one Settings UI page per chart). Thinking that @samussiah and @pburnsdata might be able to help us work through some of this part as well once we start getting in to the nitty gritty.

**Comment by bzkrouse** [comment]
Begin with data, settings, and charts for 1.0.

Possibility for sub-modules down the line when more chart types are incorporated.

**Comment by jwildfire** [comment]
Settings module implemented in v0.4. Plan is to add chart and data module in v0.5, and then consider adding "sub-modules" in future releases.
