### ISSUE TITLE
eDISH() help example produces error

### ISSUE THREAD

**Issue by bzkrouse** [ASA-DIA-InteractiveSafetyGraphics/safetyGraphics#33]
Per @jwildfire, analysisFlag should be optional, but is currently being treated as required (and the default variable is not in adlbc).

```
eDISH(data=adlbc, 
      id_col = "USUBJID",
      value_col = "AVAL", 
      measure_col = "PARAM", 
      visit_col = "VISIT",
      visitn_col = "VISITNUM", 
      studyday_col = "ADY",
      normal_col_low = "A1LO", 
      normal_col_high = "A1HI", 
      measure_values = list(ALT = "Alanine Aminotransferase (U/L)",
                            AST = "Aspartate Aminotransferase (U/L)",
                            TB = "Bilirubin (umol/L)",
                            ALP = "Alkaline Phosphatase (U/L)"))
```

![image](https://user-images.githubusercontent.com/14199771/47731686-fa477100-dc3a-11e8-8513-e18a3a20b60a.png)

**Comment by jwildfire** [comment]
The error with analysis flag is fixed in latest version, but now the examples in the `eDISH()` help both  just render as blank pages with no errors for me (tested on mac in latest commit in `shiny_dev` branch) Not sure what's going on ... Can you take a look, @bzkrouse?
