### ISSUE TITLE
update safety-edish to v0.15

### ISSUE THREAD

**Issue by jwildfire** [ASA-DIA-InteractiveSafetyGraphics/safetyGraphics#44]
A few updates coming in v0.15.0 of safety-eDish will require tweaks here: 
- `baseline_visitn` has been changed to a more general `baseline` option. 
- `visitn_col` and `visit_col` are now optional and can be removed from default settings. 

cc: @bzkrouse

**Comment by bzkrouse** [comment]
fixed here 6389124d17dc28bcf94061aeb4de94b2454bdd24
