### ISSUE TITLE
Update eDISH() example to use list of lists instead of data frame

### ISSUE THREAD

**Issue by bzkrouse** [ASA-DIA-InteractiveSafetyGraphics/safetyGraphics#50]
![image](https://user-images.githubusercontent.com/14199771/48160837-f0f77d80-e2a6-11e8-8711-b7f8b7f7a4c5.png)

**Comment by jwildfire** [comment]
`validateSettings()` doesn't support data.frames :(

Need to add support or propose an alternative ...

**Comment by jwildfire** [comment]
Changing scope of this issue to update the eDISH() example code using the notes above.
