### ISSUE TITLE
prepareChart() sets an invalid `name` parameter if none is provided

### ISSUE THREAD

**Issue by xni7** [ASA-DIA-InteractiveSafetyGraphics/safetyGraphics#636]
@jwildfire  `updateSelectizeInput()` not updating in [Example 3 of ChartConfiguration Vignette](https://github.com/SafetyGraphics/safetyGraphics/wiki/ChartConfiguration#example-3---shiny-module)

See repex below with similar nature

```r
# Shiny module example
library(safetyData) 
library(safetyGraphics)
library(dplyr)
library(yaml)
 
moduleTest_ui <- function(id) {
  ns <- NS(id) 
  wellPanel(
    actionButton(ns("b"), "update"),
    verbatimTextOutput(ns("bo")),
    numericInput(ns("test"), "Test", value = -1)
  )
}
 
 
moduleTest_server <- function(input, output, session, params) {
  
  observe({
    print(input$b)
    updateNumericInput(session = session,
                       inputId = "test",
                       value = input$b )  # or value = 99)
  })
  
  output[["bo"]] <- renderPrint({
    input$b
  })
  
}
 
 
testMod_yaml <- '
env: safetyGraphics
label: test Module
type: module
package: safetyCharts
domain: 
  - labs
workflow:
  ui: moduleTest_ui
  server: moduleTest_server
'
 
charts <- makeChartConfig() %>% purrr::keep(~.x$type == "NONE")
charts$testMod<-prepareChart(read_yaml(text=testMod_yaml))
safetyGraphicsApp(charts=charts)

```

**Comment by jwildfire** [comment]
The example in the vignette is modeled off of [this function](https://github.com/SafetyGraphics/safetyCharts/blob/dev/R/mod_safetyOutlierExplorer.R) in safetyCharts which seems to run ok still. Will look and your reprex a bit later and see if i can advise ...

**Comment by jwildfire** [comment]
Definitely seeing the bug in the reprex. Not sure what the fix is honestly ... Also strange that the code download button isn't showing up for the chart in the app. Not sure if it's related or a separate bug ...

**Comment by xni7** [comment]
Works well now!!

![image](https://user-images.githubusercontent.com/31833867/136301496-4b5af600-5682-4def-b639-f33a1db3c988.png)
