### ISSUE TITLE
Unchecking r_ratio_filter crashes chart

### ISSUE THREAD

**Issue by pburnsdata** [ASA-DIA-InteractiveSafetyGraphics/safetyGraphics#71]
Currently in the v0.4.0 dev version, if you uncheck the r_ratio_filter check box, the chart no longer renders. It's returning some error info in the browser console.

**Comment by bzkrouse** [comment]
@jwildfire - Wiki states that r_ratio_cut is ignored if r_ratio_filter is set to FALSE. I tried both:

r_ratio_filter=FALSE, r_ratio_cut=0
r_ratio_filter=FALSE, r_ratio_cut=NULL

but both produced the following error:  
Uncaught TypeError: Cannot read property 'length' of null
