### ISSUE TITLE
How to customize safety graphics app by adding our own data, creating charts and mappings section?

### ISSUE THREAD

**Issue by AlekhyaEttamsetti-14** [ASA-DIA-InteractiveSafetyGraphics/safetyGraphics#726]

**Comment by samussiah** [comment]
@AlekhyaEttamsetti-14 - the [Cookbook vignette](https://safetygraphics.github.io/safetyGraphics/articles/Cookbook.html) covers data, chart modules, and data mapping.  Let me know if you have any further questions - happy to take a look.
