### ISSUE TITLE
Changing data set in Shiny causes issues

### ISSUE THREAD

**Issue by jwildfire** [ASA-DIA-InteractiveSafetyGraphics/safetyGraphics#78]
Changing from a data set with a standard to one without doesn't work as expected. 

@bzkrouse to add details.

**Comment by bzkrouse** [comment]
Code is written to populate the dropdowns on settings UI when data changes.  If no standard is detected, we force the dropdown to default to a blank value using this code:

`sortedChoices<-colnames()
           updateSelectizeInput(session, name, choices=sortedChoices,
                                options = list(
                                  placeholder = '',
                                  onInitialize = I('function() { this.setValue(""); }')
                                ))`

If we switch back to an ADAM/SDTM dataset, the dropdowns sucessfully populate with correct options, but the blank default remains.  

Perhaps the onInitiatize statement cannot be reversed?
