### ISSUE TITLE
Allow users to save the state of the app

### ISSUE THREAD

**Issue by jwildfire** [ASA-DIA-InteractiveSafetyGraphics/safetyGraphics#8]
Perhaps with shiny bookmarks or maybe with a different method of capturing the user clicks in an audit trail.

**Comment by bzkrouse** [comment]
Other ideas:
- Generate R Markdown with code & figure (informed by user selections)
- Generate screenshot of app

**Comment by jwildfire** [comment]
Removing milestone for now, but we do need to figure this out, and document our solution before v1.0

**Comment by pburnsdata** [comment]
Adding export button to top of Chart view. 2 options initially: Copy widget code and export markdown report.

**Comment by bzkrouse** [comment]
- [parameterized R Markdown reports](https://bookdown.org/yihui/rmarkdown/parameterized-reports.html)
- [Shiny app example](https://github.com/RhoInc/safetyexploreR/tree/master/inst/shiny-examples/aeTableApp)
