### ISSUE TITLE
Add shinytest Unit Tests to App

### ISSUE THREAD

**Issue by pburnsdata** [ASA-DIA-InteractiveSafetyGraphics/safetyGraphics#95]
In the [original Travis set up](https://github.com/ASA-DIA-InteractiveSafetyGraphics/safetyGraphics/issues/76), it was decided that getting the shinytests up and running would take too long. We'll want to add these in later, through testthat or some other vehicle.

**Comment by jwildfire** [comment]
Let's do this soon. Ideally, we can use travis, but if not, we can just document a more manual workflow for now. I'm thinking we should implement the following tests: 
- Default Data
  - Settings page loads as expected. Validation passes. 
  - Chart renderers
- Load Full SDTM data
  - SDTM Standard detected. Data preview loads
  - Settings page loads as expected. Validation passes. 
  - Chart renders
- Load Partial SDTM data
  - Partial SDTM Standard detected. Data preview loads
  - Settings page loads as expected. Validation fails.
- Load Partial SDTM data + User updates settings>
  - Validation passes.  
  - Chart renders
- Load non-standard data (same tests as partial SDTM)
