### ISSUE TITLE
Update  Documentation for data files

### ISSUE THREAD

**Issue by pburnsdata** [ASA-DIA-InteractiveSafetyGraphics/safetyGraphics#96]
adding documentation for the adlbc data file was required for passing R CMD check so I added this documentation, but [as you can see](https://github.com/ASA-DIA-InteractiveSafetyGraphics/safetyGraphics/blob/travis/R/adlbc.R) it needs to be udpated.

**Comment by bzkrouse** [comment]
similar to [safetyexploreR](https://github.com/RhoInc/safetyexploreR/blob/master/R/data.R)

**Comment by jwildfire** [comment]
Need to document settingsMetadata.R as well
